require "../result"

module <%= @name.camelcase %>
  class DestroyService
    def call(id : Int64) : Services::Result(<%= @name.camelcase %>::<%= @name.camelcase %>)
      Log.info { "Destroying <%= @snake_case_name %> with ID: #{id}" }

      <%= @snake_case_name %> = <%= @name.camelcase %>::<%= @name.camelcase %>.find(id)

      if <%= @snake_case_name %>.delete
        Log.info { "Successfully destroyed <%= @snake_case_name %> with ID: #{id}" }
        Services::Result.success(<%= @snake_case_name %>)
      else
        Log.warn { "Failed to destroy <%= @snake_case_name %>: #{<%= @snake_case_name %>.errors.to_a.map(&.message).join(", ")}" }
        Services::Result.failure(<%= @snake_case_name %>.errors)
      end
    rescue CQL::RecordNotFound
      Log.warn { "<%= @name.camelcase %> with ID #{id} not found" }
      errors = CQL::ActiveRecord::Validations::Errors.new
      errors << CQL::ActiveRecord::Validations::Error.new(:base, "Record not found")
      Services::Result.failure(errors)
    rescue ex
      Log.error(exception: ex) { "Error destroying <%= @snake_case_name %> with ID #{id}" }
      errors = CQL::ActiveRecord::Validations::Errors.new
      errors << CQL::ActiveRecord::Validations::Error.new(:base, "An unexpected error occurred: #{ex.message}")
      Services::Result.failure(errors)
    end
  end
end
